--- PARTE 2
--1. Escriba una consulta en SQL que retorne la cantidad de clientes distintos por tienda que realizaron una transacción del tipo 15.

SELECT A.TIENDA, COUNT(B.RUT)
FROM POS_TRX A
INNER JOIN POS_TRX_CLIENTE B ON A.ID_TRX=B.ID_TRX
WHERE A.TIPO_TRANSACCION=15
GROUP BY TIENDA

--2. Escriba una consulta en SQL que entregue las ventas de cada tienda por año en orden de mayor a menor.

SELECT A.TIENDA,YEAR(A.FECHA_TRANSACCION) AS ANIO_TRANSACCION, COUNT(B.MONTO_PAGO) AS CANTIDAD_VENTA
FROM POS_TRX A
INNER JOIN POS_TRX_PAGO B ON A.ID_TRX=B.ID_TRX
GROUP BY TIENDA,ANIO_TRANSACCION
ORDER BY ANIO_TRANSACCION,CANTIDAD_VENTA DESC

--3. Escriba una consulta en SQL que entregue el valor de la transacción promedio de cada tienda por año en orden de mayor a menor.

SELECT A.TIENDA,YEAR(A.FECHA_TRANSACCION) AS ANIO_TRANSACCION, AVG(B.MONTO_PAGO) AS VENTA_PROMEDIO
FROM POS_TRX A
INNER JOIN POS_TRX_PAGO B ON A.ID_TRX=B.ID_TRX
GROUP BY TIENDA,ANIO_TRANSACCION
ORDER BY ANIO_TRANSACCION,VENTA_PROMEDIO DESC

--4. Escriba una consulta en SQL que responda: ¿Cuál es el principal medio de pago?

WITH TIPOS_PAGOS AS(
SELECT MEDIO_DE_PAGO,COUNT(MONTO_PAGO) AS CANTIDAD_VENTA
FROM POS_TRX_PAGO
GROUP BY MEDIO_DE_PAGO
)

SELECT MEDIO_DE_PAGO
FROM TIPOS_PAGOS
WHERE CANTIDAD_VENTA=MAX(SELECT CANTIDAD_VENTA FROM TIPOS_PAGOS)
